### ISSUE TITLE
Add seasons

### ISSUE THREAD

**Issue by Silox** [MediaGeniX/Eddy#33]
So we have a history with rankings per year, also so people can still put in their km's outside of seasons without destorting the leaderboard.

**Comment by nudded** [comment]
basically a Year field when inputting the information?

**Comment by Silox** [comment]
Yes, with start and end date and some calender range selector in the
scoreboard with defaults to select seasons and periods

**Comment by Silox** [comment]
Some stuff to think of:
- adapt user young/old scopes to the seasons
- also use them for the personal progress page
