### ISSUE TITLE
Fix deployment

### ISSUE THREAD

**Issue by nudded** [MediaGeniX/Eddy#35]
- [x] Setup toonwillems.be to point to vultr dns settings
- [x] shut down mgx-eddy.heroku.com
- [x] download backup of postgres db of heroku
- [x] create vultr instance for 5$ a month
- [x] migrate existing data
- [x] setup passenger + capistrano 
- [ ] remove deploy branch when migrated

**Comment by nudded** [comment]
@Silox the logs for production are still in nginx.log? is this a setting from passenger or from rails?

**Comment by Silox** [comment]
@nudded Fixed, some heroku gem was FUBAR
