### ISSUE TITLE
Email is not working

### ISSUE THREAD

**Issue by nudded** [MediaGeniX/Eddy#37]
The current email that would be sent shows a 500 internal error page. (kind of annoying if you forgot your password ;))

also, the mail message still includes the old URL.

**Comment by Silox** [comment]
500 is gone but sending mails takes a long long time:
I, [2017-03-10T20:05:02.174076 #2783]  INFO -- : 
Sent mail to tom.naessens@mediagenix.tv (120105.0ms)

**Comment by nudded** [comment]
Contacted support -> now solved!

**Comment by Silox** [comment]
👍
